// import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers";
// const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });


export const metadata = {
  title: "Mohammad Shahzil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
